# Generated by Django 5.2.6 on 2025-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem_address_orderitem_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
