# Generated by Django 5.2.6 on 2025-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderitem_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
