# Generated by Django 5.2.6 on 2025-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderitem_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
